# Generated by Django 3.0.4 on 2020-03-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0003_auto_20200320_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=25, null=True),
        ),
    ]
